### PR TITLE
recorder: improve tests

### LINKED ISSUE #119: POST with query arguments ?foo=bar and body (e.g. JSON) fail to match
This is a new regression from the attempt of fixing #116 . An example use case is https://ai.google.dev/gemini-api/docs/text-generation#streaming-responses, aka the equivalent of this but in Go:
```
curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:streamGenerateContent?alt=sse&key=${GEMINI_API_KEY}" \
  -H 'Content-Type: application/json' \
  --no-buffer \
  -d '{"contents": [{"parts": [{"text": "Explain how AI works"}]}]}'
```

I'll try to write a test and a fix.

### PR DESCRIPTION
**Pull request by maruel**
Test only change. No functional change.

Fixes #119.

- Use t.TempDir() instead of creating a temporary directory. The temporary directories were leaking.
- Make tests parallel to shave 70ms off test runtime on my machine. Woohoo!
- Add unit test for recording and playback with query parameters

The test verifies that POST requests with query parameters (?foo=bar&baz=true) are properly recorded and can be replayed from cassette. This ensures both the recording phase captures the query parameters in the Form field and the playback phase returns the correct response without hitting the actual server.

Change-ID: s5b05187d5bf0a5c1k

### CODE REVIEW

File: pkg/recorder/recorder_test.go [hunk 1]
```diff
@@ -1270,3 +1221,134 @@ func TestDiscardInteractionsOnSave(t *testing.T) {
...
+		if form.Get("foo") != "bar" {
+			t.Fatalf("Expected query param foo=bar, got %s", form.Get("foo"))
+		}
+		if form.Get("baz") != "true" {
+			t.Fatalf("Expected query param baz=true, got %s", form.Get("baz"))
+		}
+
+		// Phase 2: Test playback without the server running
+		// Stop the test server to ensure we're replaying from cassette
+		server.Close()
```
Comment (dnaeon) [inline pkg/recorder/recorder_test.go]: `server` will be closed already as deferred [here](https://github.com/dnaeon/go-vcr/pull/120/files#diff-fe588ee11cc9717be24fe039e82f9c963441a8829ff80d5b94eb383b3db4a7d0R1276).

File: pkg/recorder/recorder_test.go [hunk 2]
```diff
@@ -1270,3 +1221,134 @@ func TestDiscardInteractionsOnSave(t *testing.T) {
...
+		}
+		if want := "Method: POST, foo: bar, baz: true"; string(respBody) != want {
+			t.Fatalf("Recording phase: expected body %q, got %q", want, string(respBody))
+		}
+		if resp.StatusCode != http.StatusOK {
+			t.Fatalf("Recording phase: expected status %d, got %d", http.StatusOK, resp.StatusCode)
+		}
+	}
+
+	{
```
Comment (dnaeon) [inline pkg/recorder/recorder_test.go]: Any reason for the explicit scope introduced here?

**Review by dnaeon — CHANGES_REQUESTED** [review]

**Comment by dnaeon** [comment]
Hey @maruel , just kind reminder about this one. Thanks!

File: pkg/recorder/recorder_test.go (hunk 1 above)
Comment (maruel) [reply pkg/recorder/recorder_test.go]: fixed

File: pkg/recorder/recorder_test.go (hunk 2 above)
Comment (maruel) [reply pkg/recorder/recorder_test.go]: It was to make sure the variables do not alias. But you are right the defer were wrong, I converted to functions.

**Comment by dnaeon** [comment]
Thanks!
